apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: hyy0nrecx-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/hyy0nrecx-java-quarkus-gitops